group: "auto"
group_auto_prefix: ""
save_path: "checkpoints/kinetix"
use_wandb: true
save_policy: true
wandb_project: null
wandb_entity: null
wandb_mode : online
video_frequency: 10
load_from_checkpoint: null
load_only_params: true
checkpoint_save_freq: 512
checkpoint_human_numbers: false
economical_saving: false
log_buffer_freq: []