defaults:
  - env: entity
  - learning: 
    - ppo-base
    - ppo-sfl
  - misc: misc
  - ued: sfl
  - env_size: m
  - eval: m
  - eval_env_size: m
  - train_levels: random
  - model: 
    - model-base
    - model-transformer
  - _self_

eval:
  eval_freq: 128
seed: 0
use_diversity: true