defaults:
  - env: entity
  - learning: 
    - ppo-base
    - ppo-rnn
  - misc: misc
  - ued: sfl
  - env_size: s
  - eval: s
  - train_levels: random
  - model: 
    - model-base
    - model-transformer
    - model-perm-invariant-mlp
  - _self_

eval:
  eval_freq: 128
learning:
  num_steps: 256
seed: 0